//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteBrite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiteBrite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LiteBrite App was created by Artom Didinchuk..
        /// </summary>
        public static string aboutInfoString {
            get {
                return ResourceManager.GetString("aboutInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string aboutString {
            get {
                return ResourceManager.GetString("aboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutTitleString {
            get {
                return ResourceManager.GetString("aboutTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string backgroundString {
            get {
                return ResourceManager.GetString("backgroundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Height (Tiles).
        /// </summary>
        public static string boardHeightString {
            get {
                return ResourceManager.GetString("boardHeightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Width  (Tiles).
        /// </summary>
        public static string boardWidthString {
            get {
                return ResourceManager.GetString("boardWidthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelString {
            get {
                return ResourceManager.GetString("cancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string circleString {
            get {
                return ResourceManager.GetString("circleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closeString {
            get {
                return ResourceManager.GetString("closeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string colorString {
            get {
                return ResourceManager.GetString("colorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copyString {
            get {
                return ResourceManager.GetString("copyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string createString {
            get {
                return ResourceManager.GetString("createString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Settings.
        /// </summary>
        public static string dragSettingsString {
            get {
                return ResourceManager.GetString("dragSettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string exitString {
            get {
                return ResourceManager.GetString("exitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string fileString {
            get {
                return ResourceManager.GetString("fileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mosaic.
        /// </summary>
        public static string gameString {
            get {
                return ResourceManager.GetString("gameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Tiles.
        /// </summary>
        public static string generateTilesString {
            get {
                return ResourceManager.GetString("generateTilesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation Details.
        /// </summary>
        public static string generationDetailsString {
            get {
                return ResourceManager.GetString("generationDetailsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiteBrite allows you to make coulrfull image mosaics that light up.
        ///
        ///Use the controls on the right to select a mosaic tile and then click and drag to place it on the board.
        ///The board light can be toggled on and off.
        ///Drag a mosaic tile back to the origin box to copy its properties.
        ///To remove a tile drag it to the left and off the board.
        ///
        ///To create a new board use Game &gt; New menu option.
        ///(Board size is capped to 99 per side. Large board sizes can cause preformance issues)
        ///You can customize the board  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string helpContentString {
            get {
                return ResourceManager.GetString("helpContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string helpTitleString {
            get {
                return ResourceManager.GetString("helpTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Instructions.
        /// </summary>
        public static string instructionString {
            get {
                return ResourceManager.GetString("instructionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light: Off.
        /// </summary>
        public static string LightOffString {
            get {
                return ResourceManager.GetString("LightOffString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light: On.
        /// </summary>
        public static string lightOnString {
            get {
                return ResourceManager.GetString("lightOnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Tile Size.
        /// </summary>
        public static string maxMosaicSizeString {
            get {
                return ResourceManager.GetString("maxMosaicSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string moveString {
            get {
                return ResourceManager.GetString("moveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Board.
        /// </summary>
        public static string newBoardTitleString {
            get {
                return ResourceManager.GetString("newBoardTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Board.
        /// </summary>
        public static string newString {
            get {
                return ResourceManager.GetString("newString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Board.
        /// </summary>
        public static string openString {
            get {
                return ResourceManager.GetString("openString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string optionColorString {
            get {
                return ResourceManager.GetString("optionColorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string optionRandomString {
            get {
                return ResourceManager.GetString("optionRandomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string optionSizeLargeString {
            get {
                return ResourceManager.GetString("optionSizeLargeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string optionSizeMediumString {
            get {
                return ResourceManager.GetString("optionSizeMediumString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string optionSizeSmallString {
            get {
                return ResourceManager.GetString("optionSizeSmallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        public static string optionSizeTinyString {
            get {
                return ResourceManager.GetString("optionSizeTinyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Random Fill.
        /// </summary>
        public static string randomString {
            get {
                return ResourceManager.GetString("randomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Board.
        /// </summary>
        public static string saveString {
            get {
                return ResourceManager.GetString("saveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string shapeString {
            get {
                return ResourceManager.GetString("shapeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string sizeString {
            get {
                return ResourceManager.GetString("sizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string squareString {
            get {
                return ResourceManager.GetString("squareString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string swapString {
            get {
                return ResourceManager.GetString("swapString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiteBrite.
        /// </summary>
        public static string titleString {
            get {
                return ResourceManager.GetString("titleString", resourceCulture);
            }
        }
    }
}
